INFO:urllib3.connectionpool:Starting new HTTPS connection (1): www.jbhifi.com.au
DEBUG:urllib3.connectionpool:"HEAD /whitegoods-appliances/kitchen-appliances/breville/breville-the-juice-fountain-compact-juicer/34198/ HTTP/1.1" 200 0
INFO:urllib3.connectionpool:Starting new HTTPS connection (1): www.jbhifi.com.au
DEBUG:urllib3.connectionpool:"GET /whitegoods-appliances/kitchen-appliances/breville/breville-the-juice-fountain-compact-juicer/34198/ HTTP/1.1" 200 29168
INFO:urllib3.connectionpool:Starting new HTTPS connection (1): www.jbhifi.com.au
DEBUG:urllib3.connectionpool:"HEAD /whitegoods-appliances/vacuums-floor-cleaners/dyson/dyson-turbine-head/29572/ HTTP/1.1" 200 0
INFO:urllib3.connectionpool:Starting new HTTPS connection (1): www.jbhifi.com.au
DEBUG:urllib3.connectionpool:"GET /whitegoods-appliances/vacuums-floor-cleaners/dyson/dyson-turbine-head/29572/ HTTP/1.1" 200 27104
INFO:urllib3.connectionpool:Starting new HTTPS connection (1): www.jbhifi.com.au
DEBUG:urllib3.connectionpool:"HEAD /whitegoods-appliances/fridges-freezers/westinghouse/westinghouse-wrm1300wc-130l-bar-fridge/27694/ HTTP/1.1" 200 0
INFO:urllib3.connectionpool:Starting new HTTPS connection (1): www.jbhifi.com.au
DEBUG:urllib3.connectionpool:"GET /whitegoods-appliances/fridges-freezers/westinghouse/westinghouse-wrm1300wc-130l-bar-fridge/27694/ HTTP/1.1" 200 28485
INFO:urllib3.connectionpool:Starting new HTTPS connection (1): www.jbhifi.com.au
DEBUG:urllib3.connectionpool:"HEAD /whitegoods-appliances/vacuums-floor-cleaners/dyson/dyson-car-cleaning-kit/30086/ HTTP/1.1" 200 0
INFO:urllib3.connectionpool:Starting new HTTPS connection (1): www.jbhifi.com.au
DEBUG:urllib3.connectionpool:"GET /whitegoods-appliances/vacuums-floor-cleaners/dyson/dyson-car-cleaning-kit/30086/ HTTP/1.1" 200 27408
INFO:urllib3.connectionpool:Starting new HTTPS connection (1): www.jbhifi.com.au
DEBUG:urllib3.connectionpool:"HEAD /whitegoods-appliances/kitchen-appliances/breville/breville-the-adjusta-grill-press/63426/ HTTP/1.1" 200 0
INFO:urllib3.connectionpool:Starting new HTTPS connection (1): www.jbhifi.com.au
DEBUG:urllib3.connectionpool:"GET /whitegoods-appliances/kitchen-appliances/breville/breville-the-adjusta-grill-press/63426/ HTTP/1.1" 200 28216
INFO:urllib3.connectionpool:Starting new HTTPS connection (1): www.jbhifi.com.au
ERROR:root:ERROR
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 516, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 304, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 724, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 237, in connect
    ssl_version=resolved_ssl_version)
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 123, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket
    _context=self)
  File "/usr/lib/python3.4/ssl.py", line 577, in __init__
    self.do_handshake()
  File "/usr/lib/python3.4/ssl.py", line 804, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 362, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 543, in urlopen
    raise SSLError(e)
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tupperware/JBHIFIWebCrawler/Programs/JBHIFIPriceAnalyser.py", line 212, in <module>
    database_analyser()
  File "/home/tupperware/JBHIFIWebCrawler/Programs/JBHIFIPriceAnalyser.py", line 104, in database_analyser
    res = requests.head(url)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 82, in head
    return request('head', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 49, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 420, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)
