INFO:urllib3.connectionpool:Starting new HTTPS connection (1): www.jbhifi.com.au
DEBUG:urllib3.connectionpool:"HEAD /whitegoods-appliances/cooking/westinghouse/westinghouse-wrj911us-900mm-fixed-2-fan-rangehood-s-steel/45955/ HTTP/1.1" 200 0
INFO:urllib3.connectionpool:Starting new HTTPS connection (1): www.jbhifi.com.au
DEBUG:urllib3.connectionpool:"GET /whitegoods-appliances/cooking/westinghouse/westinghouse-wrj911us-900mm-fixed-2-fan-rangehood-s-steel/45955/ HTTP/1.1" 200 27603
ERROR:root:ERROR
Traceback (most recent call last):
  File "/home/tupperware/JBHIFIWebCrawler/Programs/JBHIFIPriceAnalyser.py", line 212, in <module>
    database_analyser()
  File "/home/tupperware/JBHIFIWebCrawler/Programs/JBHIFIPriceAnalyser.py", line 187, in database_analyser
    c.execute("INSERT INTO productPricing VALUES(%s, %s, %s, %s, %s, %s)",(str(productPageID), str(date), str(price), str(overallRating), str(numberReviews), str(isActive)))
  File "/usr/local/lib/python3.4/dist-packages/mysql/connector/cursor.py", line 515, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/usr/local/lib/python3.4/dist-packages/mysql/connector/connection.py", line 488, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/usr/local/lib/python3.4/dist-packages/mysql/connector/connection.py", line 395, in _handle_result
    raise errors.get_exception(packet)
mysql.connector.errors.IntegrityError: 1062 (23000): Duplicate entry '268259-2017-03-20' for key 'PRIMARY'
